//font wont fit in screen, need to compress it
//maldives slide deletes title

var imageSelect;
var imageType = "";

var imagesGallery = [];

var backgroundImage;


function setup() {
  // put setup code here
  createCanvas(900,650);




  backgroundImage = loadImage("images/airplane.jpg");

  imagesGallery[0]=loadImage("images/Santorini.jpg");;
  imagesGallery[1]=loadImage("images/Galapagos.jpg");;
  imagesGallery[2]=loadImage("images/Palawan.jpg");;
  imagesGallery[3]=loadImage("images/BoraBora.jpg");;
  imagesGallery[4]=loadImage("images/Maldives.jpg");;

imageSelect = createSelect();
imageSelect.position(10,10);
imageSelect.option("");
imageSelect.option("Santorini");
imageSelect.option("Galapagos");
imageSelect.option("Palawan");
imageSelect.option("BoraBora");
imageSelect.option("Maldives");
imageSelect.changed(function(){

imageType = imageSelect.value();

  });

}//end of set up



function draw() {
  // put drawing code here
  background(backgroundImage);


if(imageType == "Santorini"){
  console.log("Santorini");
  image(imagesGallery[0],0,0);
  text("Possibly the most beautiful island in Greece, Santorini is famous for its fantastic sunsets, rivaling most others around the world. Santorini is home to beaches of black, red and white sand making each trip to the beach exceptional and unique. It is known for its water sports for anyone who enjoys diving, water skiing, parasailing or wakeboarding. Santorini is also filled with beautiful architecture built right into the cliffs of the island, with amazing restaurants, shops and nightlife.",10,70, 500,300);




}if(imageType == "Galapagos"){
  console.log("Galapagos");
  image(imagesGallery[1],0,0);
  text("The Galapagos, located in Equador, is without a doubt one the most popular wildlife destinations and one of the most beautiful islands in the world. Consisting of eighteen main islands and three smaller ones, it is one of the few places in the world barely touched by humans as its fragile ecosystem is protected by the government. It is home to the Galapagos tortoise, marine iguana, Galapagos fur seal, galápagos penguin, Galapagos hawk and many more thriving species. Known for its gorgeous beaches with white sand and beautiful blue water, one can enjoy snorkeling, diving, kayaking and more.",40,60,800,300);



}if(imageType == "Palawan"){
  console.log("Palawan");
  image(imagesGallery[2],0,0);
  text("Palawan is certainly the most stunning island in the Philippines. Its coastline stretches over 1240 miles and holds many unspoiled beaches in Palawan with crystal clear water. Palawan is also home to Puerto-Princesa, a 5-mile long underground river, making it the longest navigable underground river in the world. Palawan also has spectacular rainforests, mangroves, several rivers, streams, lakes, and waterfalls to explore.",240,80,500,300);


}if(imageType == "BoraBora"){
  console.log("BoraBora");
  image(imagesGallery[3],0,0);
  text("Bora Bora is the most famous and beautiful island in French Polynesia and is a world-renowned honeymoon destination. It is also perfect for traveling alone or with family. It is surrounded by one of the most beautiful lagoons in the world, with white sandy beaches and beautiful emerald and blue colored waters that often feel unreal to visitors. It is the perfect place to relax, but also known to many for its water sports including aqua bike adventures, glass bottom boat tours, parasailing, jet skiing, lagoon cruises, snorkeling, scuba diving and stand-up paddling.",10,70,500,300);



}if(imageType == "Maldives"){
  console.log("Maldives");
  image(imagesGallery[4],0,0);
  text("Maldives is very likely the most beautiful island in the world. Found in the Indian Ocean, this spectacular destination consists of more than 1000 coral islands. It is known for its white sand, clear water beaches, lagoons, coral reefs and marine life that is unparalleled and too beautiful to describe. One of the most exciting attractions being Vaadhoo Island where one can enjoy naturally glittering waters generated by the plankton population there. It is also home to many fun water activities like diving, boat tours, snorkeling, kayaking and more. Maldives is a place fit for anyone to come relax and enjoy its peaceful beauty as well as those looking to explore and adventure. It is truly a place that will leave you speechless.",10,70,400,300);

}

else{
  console.log("blank");
  text("The most beauitful islands in the world", 290, 20);
  fill(0);
  textSize(10);
  textFont('Georgia');


  text("Select the Island you would like to visit", 10, 50);
  fill(0);
  textSize(18);
  textFont('Georgia');
}





}//end of draw loop
